### ISSUE TITLE
Error in WordPress FAQ Code

### ISSUE THREAD

**Issue by StanfordAlan** [ibericode/mailchimp-top-bar#71] opened 2017-07-02 11:03 UTC
I hope this is the right spot to note this:

In the FAQ section of your plugin's page on WordPress.org, there's a problem. https://wordpress.org/plugins/mailchimp-top-bar/

Under "How to hide the bar on small screens," you have part of the CSS list. It actually finishes as the next top of the FAQ instead of being all together. 

Here's a screenshot of the issue: https://www.screencast.com/t/Rnua5MGc

Thank you.

**Comment by dannyvankooten** [comment] 2017-07-06 08:09
Thanks for the heads up @StanfordAlan, looks like the new wp.org layout caused this. We'll be looking into it!

**Comment by dannyvankooten** [comment] 2017-10-25 07:01
Duplicate of #74, fixed by #75

**Closed by dannyvankooten** 2017-10-25 07:01 UTC
Labels: bug
