### ISSUE TITLE
Ability to exclude from specific pages

### ISSUE THREAD

**Issue by amaragrimes** [ibericode/mailchimp-top-bar#36] opened 2015-07-01 22:51 UTC
Self-explanatory. This occurred to me when creating a "Thank you for subscribing" page -- would like to exclude the bar in that instance.

**Comment by dannyvankooten** [comment] 2015-07-02 07:29
Hi @amaragrimes ,

Good one - this is definitely on the list of things to build!

Please note that for now you can do this using the `mctb_show_bar` filter. The following is an example that will show the bar on all pages EXCEPT the `contact` page.

```php
add_filter( 'mctb_show_bar', function( $show ) {
    return ! is_page( 'contact' );
} );
```

Hope that helps!

Closing this issue because it is a duplicate of #8 .

**Closed by dannyvankooten** 2015-07-02 07:29 UTC
